# Generated by Django 3.0.6 on 2020-06-24 11:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CoursesMS', '0001_initial'),
        ('StudentsMS', '0002_attendance'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='CoursesMS.Course'),
        ),
    ]
