# Generated by Django 3.0.6 on 2020-06-23 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=50, unique=True)),
                ('course_code', models.CharField(max_length=6, unique=True)),
                ('course_semster', models.CharField(choices=[('first semster', '1'), ('secode semster', '2')], max_length=20)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('cridit_hours', models.IntegerField(null=True)),
            ],
        ),
    ]
